// Generated by gencpp from file my_first_pkg/custom.msg
// DO NOT EDIT!


#ifndef MY_FIRST_PKG_MESSAGE_CUSTOM_H
#define MY_FIRST_PKG_MESSAGE_CUSTOM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_first_pkg
{
template <class ContainerAllocator>
struct custom_
{
  typedef custom_<ContainerAllocator> Type;

  custom_()
    : x(0)
    , y(0.0)
    , str()  {
    }
  custom_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0.0)
    , str(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _str_type;
  _str_type str;





  typedef boost::shared_ptr< ::my_first_pkg::custom_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_first_pkg::custom_<ContainerAllocator> const> ConstPtr;

}; // struct custom_

typedef ::my_first_pkg::custom_<std::allocator<void> > custom;

typedef boost::shared_ptr< ::my_first_pkg::custom > customPtr;
typedef boost::shared_ptr< ::my_first_pkg::custom const> customConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_first_pkg::custom_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_first_pkg::custom_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_first_pkg::custom_<ContainerAllocator1> & lhs, const ::my_first_pkg::custom_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.str == rhs.str;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_first_pkg::custom_<ContainerAllocator1> & lhs, const ::my_first_pkg::custom_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_first_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::my_first_pkg::custom_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_first_pkg::custom_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_first_pkg::custom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_first_pkg::custom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_first_pkg::custom_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_first_pkg::custom_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_first_pkg::custom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cdd8807acedfe4bc483e70beedd18e21";
  }

  static const char* value(const ::my_first_pkg::custom_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcdd8807acedfe4bcULL;
  static const uint64_t static_value2 = 0x483e70beedd18e21ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_first_pkg::custom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_first_pkg/custom";
  }

  static const char* value(const ::my_first_pkg::custom_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_first_pkg::custom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 x\n"
"float64 y\n"
"string str\n"
;
  }

  static const char* value(const ::my_first_pkg::custom_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_first_pkg::custom_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.str);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct custom_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_first_pkg::custom_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_first_pkg::custom_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int64_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "str: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.str);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_FIRST_PKG_MESSAGE_CUSTOM_H
